const videoList = [
  { title: "The fungus Aspergillus niger growing fruiting bodies at 10x magnification. Video by Wim van Egmond.", link: "https://i.imgur.com/FDT2jp5.mp4" },
  { title: "Chromataphores in squid mantle at 4x magnification. Video by Bill Shin.", link: "https://i.imgur.com/lSpFsxe.mp4" },
  { title: "Green Stentor coeruleus and Vorticella at 25x magnification. Video by Frank Fox.", link: "https://i.imgur.com/ENiRikD.mp4" },
  { title: "A ciliate from genus Pseudomicrothorax devours a cyanobacterial filament at 20x and 40x magnification. Video by Dr. Sally Warring.", link: "https://i.imgur.com/cTQqlEk.mp4" },
  { title: "The rotifer Limnias melicerta at 200x magnification. Video by Wim van Egmond.", link: "https://i.imgur.com/iIntJym.mp4" },
  { title: "Polychaete worm of the Syllidae family at 20x and 40x magnification. Video by Rafael Martín-Ledo.", link: "https://i.imgur.com/R4UIzum.mp4" },
  { title: "Lightning strike on the coast of Montenegro", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916489/video/lightning_ssci4j.mp4" },
  { title: "Hawkmoth", link: "https://i.imgur.com/NudotTQ.mp4" },
  { title: "Friendly deer", link: "https://i.imgur.com/vJ5PXiR.mp4" },
  { title: "mini horse", link: "https://i.imgur.com/oXV1dQ1.mp4" },
  { title: "opossums", link: "https://i.imgur.com/QtoenRl.mp4" },
  { title: "cracking geode", link: "https://i.imgur.com/LO3T7QN.mp4" },
  { title: "swimming crab", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916590/video/swimming-crab_jhkbjm.mp4" },
  { title: "snail", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916537/video/snail_nrczqp.mp4" },
  { title: "sunset", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916503/video/sunset_sl5ja3.mp4" },
  { title: "high voltage", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916486/video/high-voltage_rmpppr.mp4" },
  { title: "rafflesia", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916479/video/rafflesia_u2l00z.mp4" },
  { title: "turtle", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916576/video/turtles_yu3bw4.mp4" },
  { title: "mower", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916514/video/mower_gwf4g9.mp4" },
  { title: "matrix", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916577/video/matrix_copy_j8yvzu.mp4" },
  { title: "horses farting", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916590/video/horses-farting_dxnc9l.mp4" },
  { title: "sea slugs", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916592/video/sea-slug_gpteew.mp4" },
  { title: "elephants crushing pumpkins", link: "https://res.cloudinary.com/dd5bgygfp/video/upload/v1701916583/video/elephant-pumpkin_v5w02l.mp4" },
  // { title: "", link: "" },
];

export default videoList;